### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by Mikemosca**
Also, reorganized the test directory to contain unit and integration
directories.  This is something Nathan and I did in the document
conversion repo.  Would be nice to follow this convention for all repos.

### CODE REVIEW

**Comment by Mikemosca** [comment]
@germanattanasio - not sure why the integration tests fails here with username/password issue.  I did do a test build and it worked fine for me.

**Comment by Mikemosca** [comment]
@germanattanasio - Another question is how do we publish the code coverage stats on the README page?  

screen shot 2016-11-03 at 2 24 02 pm

I see for visual recognition repo they are there.

screen shot 2016-11-03 at 2 25 38 pm

**Comment by germanattanasio** [comment]
Let me see

**Comment by germanattanasio** [comment]
@Mikemosca you forgot to add `casperjs` to the dependencies in the `package.json`
```
npm install casperjs --save-dev
```

**Pull request merged**
